description: "Half-day Workshop ECC24 @ Stockholm, Sweden<br/> 25 June 2024"
theme: jekyll-theme-cayman
title: "Task and Motion Coordination <br/> under Geometric, Dynamic and <br/> Temporal Constraints (TMC+X)"
